name = "test-durable-object-rpc"
main = "worker.ts"
compatibility_date = "2024-04-03"

[durable_objects]
bindings = [
  { name = "TEST_RPC_DO", class_name = "TestRpcDurableObject" },
  { name = "TEST_RPC_CLIENT_DO", class_name = "TestRpcClientDO" },
]

[[migrations]]
tag = "v1"
new_classes = ["TestRpcDurableObject", "TestRpcClientDO"]
