/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DerivedDefaultWithReadinessMarkerRouteImport } from './routes/derived/default-with-readiness-marker'
import { Route as ClientOnlyUseEnsureClientDocumentsSuspenseRouteImport } from './routes/client-only/use-ensure-client-documents-suspense'
import { Route as ClientOnlyUseEnsureClientDocumentsRouteImport } from './routes/client-only/use-ensure-client-documents'
import { Route as ClientOnlySuspenseStoreBootRouteImport } from './routes/client-only/suspense-store-boot'
import { Route as ClientOnlyEnsureClientDocumentSuspenseBoundaryRouteImport } from './routes/client-only/ensure-client-document-suspense-boundary'
import { Route as ClientOnlyRouteLoaderEnsureMailboxIdRouteImport } from './routes/client-only/route-loader-ensure.$mailboxId'
import { Route as ClientOnlyComponentEnsureIfReadyMailboxIdRouteImport } from './routes/client-only/component-ensure-if-ready.$mailboxId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivedDefaultWithReadinessMarkerRoute =
  DerivedDefaultWithReadinessMarkerRouteImport.update({
    id: '/derived/default-with-readiness-marker',
    path: '/derived/default-with-readiness-marker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyUseEnsureClientDocumentsSuspenseRoute =
  ClientOnlyUseEnsureClientDocumentsSuspenseRouteImport.update({
    id: '/client-only/use-ensure-client-documents-suspense',
    path: '/client-only/use-ensure-client-documents-suspense',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyUseEnsureClientDocumentsRoute =
  ClientOnlyUseEnsureClientDocumentsRouteImport.update({
    id: '/client-only/use-ensure-client-documents',
    path: '/client-only/use-ensure-client-documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlySuspenseStoreBootRoute =
  ClientOnlySuspenseStoreBootRouteImport.update({
    id: '/client-only/suspense-store-boot',
    path: '/client-only/suspense-store-boot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute =
  ClientOnlyEnsureClientDocumentSuspenseBoundaryRouteImport.update({
    id: '/client-only/ensure-client-document-suspense-boundary',
    path: '/client-only/ensure-client-document-suspense-boundary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyRouteLoaderEnsureMailboxIdRoute =
  ClientOnlyRouteLoaderEnsureMailboxIdRouteImport.update({
    id: '/client-only/route-loader-ensure/$mailboxId',
    path: '/client-only/route-loader-ensure/$mailboxId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyComponentEnsureIfReadyMailboxIdRoute =
  ClientOnlyComponentEnsureIfReadyMailboxIdRouteImport.update({
    id: '/client-only/component-ensure-if-ready/$mailboxId',
    path: '/client-only/component-ensure-if-ready/$mailboxId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-only/ensure-client-document-suspense-boundary': typeof ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute
  '/client-only/suspense-store-boot': typeof ClientOnlySuspenseStoreBootRoute
  '/client-only/use-ensure-client-documents': typeof ClientOnlyUseEnsureClientDocumentsRoute
  '/client-only/use-ensure-client-documents-suspense': typeof ClientOnlyUseEnsureClientDocumentsSuspenseRoute
  '/derived/default-with-readiness-marker': typeof DerivedDefaultWithReadinessMarkerRoute
  '/client-only/component-ensure-if-ready/$mailboxId': typeof ClientOnlyComponentEnsureIfReadyMailboxIdRoute
  '/client-only/route-loader-ensure/$mailboxId': typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-only/ensure-client-document-suspense-boundary': typeof ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute
  '/client-only/suspense-store-boot': typeof ClientOnlySuspenseStoreBootRoute
  '/client-only/use-ensure-client-documents': typeof ClientOnlyUseEnsureClientDocumentsRoute
  '/client-only/use-ensure-client-documents-suspense': typeof ClientOnlyUseEnsureClientDocumentsSuspenseRoute
  '/derived/default-with-readiness-marker': typeof DerivedDefaultWithReadinessMarkerRoute
  '/client-only/component-ensure-if-ready/$mailboxId': typeof ClientOnlyComponentEnsureIfReadyMailboxIdRoute
  '/client-only/route-loader-ensure/$mailboxId': typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-only/ensure-client-document-suspense-boundary': typeof ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute
  '/client-only/suspense-store-boot': typeof ClientOnlySuspenseStoreBootRoute
  '/client-only/use-ensure-client-documents': typeof ClientOnlyUseEnsureClientDocumentsRoute
  '/client-only/use-ensure-client-documents-suspense': typeof ClientOnlyUseEnsureClientDocumentsSuspenseRoute
  '/derived/default-with-readiness-marker': typeof DerivedDefaultWithReadinessMarkerRoute
  '/client-only/component-ensure-if-ready/$mailboxId': typeof ClientOnlyComponentEnsureIfReadyMailboxIdRoute
  '/client-only/route-loader-ensure/$mailboxId': typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-only/ensure-client-document-suspense-boundary'
    | '/client-only/suspense-store-boot'
    | '/client-only/use-ensure-client-documents'
    | '/client-only/use-ensure-client-documents-suspense'
    | '/derived/default-with-readiness-marker'
    | '/client-only/component-ensure-if-ready/$mailboxId'
    | '/client-only/route-loader-ensure/$mailboxId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-only/ensure-client-document-suspense-boundary'
    | '/client-only/suspense-store-boot'
    | '/client-only/use-ensure-client-documents'
    | '/client-only/use-ensure-client-documents-suspense'
    | '/derived/default-with-readiness-marker'
    | '/client-only/component-ensure-if-ready/$mailboxId'
    | '/client-only/route-loader-ensure/$mailboxId'
  id:
    | '__root__'
    | '/'
    | '/client-only/ensure-client-document-suspense-boundary'
    | '/client-only/suspense-store-boot'
    | '/client-only/use-ensure-client-documents'
    | '/client-only/use-ensure-client-documents-suspense'
    | '/derived/default-with-readiness-marker'
    | '/client-only/component-ensure-if-ready/$mailboxId'
    | '/client-only/route-loader-ensure/$mailboxId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute: typeof ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute
  ClientOnlySuspenseStoreBootRoute: typeof ClientOnlySuspenseStoreBootRoute
  ClientOnlyUseEnsureClientDocumentsRoute: typeof ClientOnlyUseEnsureClientDocumentsRoute
  ClientOnlyUseEnsureClientDocumentsSuspenseRoute: typeof ClientOnlyUseEnsureClientDocumentsSuspenseRoute
  DerivedDefaultWithReadinessMarkerRoute: typeof DerivedDefaultWithReadinessMarkerRoute
  ClientOnlyComponentEnsureIfReadyMailboxIdRoute: typeof ClientOnlyComponentEnsureIfReadyMailboxIdRoute
  ClientOnlyRouteLoaderEnsureMailboxIdRoute: typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derived/default-with-readiness-marker': {
      id: '/derived/default-with-readiness-marker'
      path: '/derived/default-with-readiness-marker'
      fullPath: '/derived/default-with-readiness-marker'
      preLoaderRoute: typeof DerivedDefaultWithReadinessMarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/use-ensure-client-documents-suspense': {
      id: '/client-only/use-ensure-client-documents-suspense'
      path: '/client-only/use-ensure-client-documents-suspense'
      fullPath: '/client-only/use-ensure-client-documents-suspense'
      preLoaderRoute: typeof ClientOnlyUseEnsureClientDocumentsSuspenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/use-ensure-client-documents': {
      id: '/client-only/use-ensure-client-documents'
      path: '/client-only/use-ensure-client-documents'
      fullPath: '/client-only/use-ensure-client-documents'
      preLoaderRoute: typeof ClientOnlyUseEnsureClientDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/suspense-store-boot': {
      id: '/client-only/suspense-store-boot'
      path: '/client-only/suspense-store-boot'
      fullPath: '/client-only/suspense-store-boot'
      preLoaderRoute: typeof ClientOnlySuspenseStoreBootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/ensure-client-document-suspense-boundary': {
      id: '/client-only/ensure-client-document-suspense-boundary'
      path: '/client-only/ensure-client-document-suspense-boundary'
      fullPath: '/client-only/ensure-client-document-suspense-boundary'
      preLoaderRoute: typeof ClientOnlyEnsureClientDocumentSuspenseBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/route-loader-ensure/$mailboxId': {
      id: '/client-only/route-loader-ensure/$mailboxId'
      path: '/client-only/route-loader-ensure/$mailboxId'
      fullPath: '/client-only/route-loader-ensure/$mailboxId'
      preLoaderRoute: typeof ClientOnlyRouteLoaderEnsureMailboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/component-ensure-if-ready/$mailboxId': {
      id: '/client-only/component-ensure-if-ready/$mailboxId'
      path: '/client-only/component-ensure-if-ready/$mailboxId'
      fullPath: '/client-only/component-ensure-if-ready/$mailboxId'
      preLoaderRoute: typeof ClientOnlyComponentEnsureIfReadyMailboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute:
    ClientOnlyEnsureClientDocumentSuspenseBoundaryRoute,
  ClientOnlySuspenseStoreBootRoute: ClientOnlySuspenseStoreBootRoute,
  ClientOnlyUseEnsureClientDocumentsRoute:
    ClientOnlyUseEnsureClientDocumentsRoute,
  ClientOnlyUseEnsureClientDocumentsSuspenseRoute:
    ClientOnlyUseEnsureClientDocumentsSuspenseRoute,
  DerivedDefaultWithReadinessMarkerRoute:
    DerivedDefaultWithReadinessMarkerRoute,
  ClientOnlyComponentEnsureIfReadyMailboxIdRoute:
    ClientOnlyComponentEnsureIfReadyMailboxIdRoute,
  ClientOnlyRouteLoaderEnsureMailboxIdRoute:
    ClientOnlyRouteLoaderEnsureMailboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
