/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DerivedDefaultWithReadinessMarkerRouteImport } from './routes/derived/default-with-readiness-marker'
import { Route as ClientOnlyUseClientDocumentsPreflightRouteImport } from './routes/client-only/use-client-documents-preflight'
import { Route as ClientOnlyClientDocumentPreflightRouteImport } from './routes/client-only/client-document-preflight'
import { Route as ClientOnlyBootEnsureRouteImport } from './routes/client-only/boot-ensure'
import { Route as ClientOnlyRouteLoaderEnsureMailboxIdRouteImport } from './routes/client-only/route-loader-ensure.$mailboxId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivedDefaultWithReadinessMarkerRoute =
  DerivedDefaultWithReadinessMarkerRouteImport.update({
    id: '/derived/default-with-readiness-marker',
    path: '/derived/default-with-readiness-marker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyUseClientDocumentsPreflightRoute =
  ClientOnlyUseClientDocumentsPreflightRouteImport.update({
    id: '/client-only/use-client-documents-preflight',
    path: '/client-only/use-client-documents-preflight',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyClientDocumentPreflightRoute =
  ClientOnlyClientDocumentPreflightRouteImport.update({
    id: '/client-only/client-document-preflight',
    path: '/client-only/client-document-preflight',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientOnlyBootEnsureRoute = ClientOnlyBootEnsureRouteImport.update({
  id: '/client-only/boot-ensure',
  path: '/client-only/boot-ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOnlyRouteLoaderEnsureMailboxIdRoute =
  ClientOnlyRouteLoaderEnsureMailboxIdRouteImport.update({
    id: '/client-only/route-loader-ensure/$mailboxId',
    path: '/client-only/route-loader-ensure/$mailboxId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-only/boot-ensure': typeof ClientOnlyBootEnsureRoute
  '/client-only/client-document-preflight': typeof ClientOnlyClientDocumentPreflightRoute
  '/client-only/use-client-documents-preflight': typeof ClientOnlyUseClientDocumentsPreflightRoute
  '/derived/default-with-readiness-marker': typeof DerivedDefaultWithReadinessMarkerRoute
  '/client-only/route-loader-ensure/$mailboxId': typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-only/boot-ensure': typeof ClientOnlyBootEnsureRoute
  '/client-only/client-document-preflight': typeof ClientOnlyClientDocumentPreflightRoute
  '/client-only/use-client-documents-preflight': typeof ClientOnlyUseClientDocumentsPreflightRoute
  '/derived/default-with-readiness-marker': typeof DerivedDefaultWithReadinessMarkerRoute
  '/client-only/route-loader-ensure/$mailboxId': typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-only/boot-ensure': typeof ClientOnlyBootEnsureRoute
  '/client-only/client-document-preflight': typeof ClientOnlyClientDocumentPreflightRoute
  '/client-only/use-client-documents-preflight': typeof ClientOnlyUseClientDocumentsPreflightRoute
  '/derived/default-with-readiness-marker': typeof DerivedDefaultWithReadinessMarkerRoute
  '/client-only/route-loader-ensure/$mailboxId': typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-only/boot-ensure'
    | '/client-only/client-document-preflight'
    | '/client-only/use-client-documents-preflight'
    | '/derived/default-with-readiness-marker'
    | '/client-only/route-loader-ensure/$mailboxId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-only/boot-ensure'
    | '/client-only/client-document-preflight'
    | '/client-only/use-client-documents-preflight'
    | '/derived/default-with-readiness-marker'
    | '/client-only/route-loader-ensure/$mailboxId'
  id:
    | '__root__'
    | '/'
    | '/client-only/boot-ensure'
    | '/client-only/client-document-preflight'
    | '/client-only/use-client-documents-preflight'
    | '/derived/default-with-readiness-marker'
    | '/client-only/route-loader-ensure/$mailboxId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientOnlyBootEnsureRoute: typeof ClientOnlyBootEnsureRoute
  ClientOnlyClientDocumentPreflightRoute: typeof ClientOnlyClientDocumentPreflightRoute
  ClientOnlyUseClientDocumentsPreflightRoute: typeof ClientOnlyUseClientDocumentsPreflightRoute
  DerivedDefaultWithReadinessMarkerRoute: typeof DerivedDefaultWithReadinessMarkerRoute
  ClientOnlyRouteLoaderEnsureMailboxIdRoute: typeof ClientOnlyRouteLoaderEnsureMailboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derived/default-with-readiness-marker': {
      id: '/derived/default-with-readiness-marker'
      path: '/derived/default-with-readiness-marker'
      fullPath: '/derived/default-with-readiness-marker'
      preLoaderRoute: typeof DerivedDefaultWithReadinessMarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/use-client-documents-preflight': {
      id: '/client-only/use-client-documents-preflight'
      path: '/client-only/use-client-documents-preflight'
      fullPath: '/client-only/use-client-documents-preflight'
      preLoaderRoute: typeof ClientOnlyUseClientDocumentsPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/client-document-preflight': {
      id: '/client-only/client-document-preflight'
      path: '/client-only/client-document-preflight'
      fullPath: '/client-only/client-document-preflight'
      preLoaderRoute: typeof ClientOnlyClientDocumentPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/boot-ensure': {
      id: '/client-only/boot-ensure'
      path: '/client-only/boot-ensure'
      fullPath: '/client-only/boot-ensure'
      preLoaderRoute: typeof ClientOnlyBootEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-only/route-loader-ensure/$mailboxId': {
      id: '/client-only/route-loader-ensure/$mailboxId'
      path: '/client-only/route-loader-ensure/$mailboxId'
      fullPath: '/client-only/route-loader-ensure/$mailboxId'
      preLoaderRoute: typeof ClientOnlyRouteLoaderEnsureMailboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientOnlyBootEnsureRoute: ClientOnlyBootEnsureRoute,
  ClientOnlyClientDocumentPreflightRoute:
    ClientOnlyClientDocumentPreflightRoute,
  ClientOnlyUseClientDocumentsPreflightRoute:
    ClientOnlyUseClientDocumentsPreflightRoute,
  DerivedDefaultWithReadinessMarkerRoute:
    DerivedDefaultWithReadinessMarkerRoute,
  ClientOnlyRouteLoaderEnsureMailboxIdRoute:
    ClientOnlyRouteLoaderEnsureMailboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
