name = "livestore-cf-adapter-chat"
main = "src/cf-worker/index.ts"
compatibility_date = "2025-08-24"

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[[d1_databases]]
binding = "DB"
database_name = "cf-chat-demo"
database_id = "3335b917-2c3f-4c3c-a04f-78d74d46c141"

[observability]
enabled = true
