name = "livestore-cf-adapter-chat"
main = "src/cf-worker/index.ts"
compatibility_date = "2025-08-24"
compatibility_flags = [
  "enable_request_signal", # Needed for HTTP RPC streams
  "nodejs_compat", # needed for @opentelemetry/*
]
preview_urls = true

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[observability]
enabled = true
