name = "web-linearlite-sync"
main = "./src/server.ts"
compatibility_date = "2025-05-08"
compatibility_flags = [
  "enable_request_signal", # Needed for HTTP RPC streams
  "nodejs_compat", # needed for @opentelemetry/*
]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
