name: Setup
description: Setup the environment for the CI workflow.
# inputs:
#   node-version:
#     description: The version of Node.js to install
#     required: true
#     default: 23.7.0

runs:
  using: composite
  steps:
    - name: Install Determinate Nix
      uses: DeterminateSystems/determinate-nix-action@v3

      # NOTE Flakehub cache is still faster than magic-nix-cache-action
    - name: Setup Flakehub Cache
      uses: DeterminateSystems/flakehub-cache-action@main
    # - name: Nix cache
    #   uses: DeterminateSystems/magic-nix-cache-action@main

    # Speed up direnv setup by caching the binary
    - name: Cache direnv binary
      uses: actions/cache@v4
      with:
        path: ~/.nix-profile/bin/direnv
        key: direnv-${{ runner.os }}-${{ hashFiles('.envrc') }}
        restore-keys: |
          direnv-${{ runner.os }}-

    # We're timing out after 5 minutes in case Nix wants to rebuild something which could burn a lot of CPU time
    - name: Install + load direnv env
      shell: bash
      run: |
        nix profile install nixpkgs#direnv
        # Setup direnv shell integration for subsequent steps
        echo 'eval "$(direnv hook bash)"' >>"$BASH_ENV"
        timeout 300 direnv allow
        # Make env vars available to subsequent steps
        direnv dump >>"$GITHUB_ENV"
