packages:
  - scripts
  - docs
  - packages/@livestore/*
  - packages/@local/*
  - examples/*
  - tests/*

catalog:
  # Type packages
  "@types/react": ^19.1.11
  "@types/react-dom": ^19.1.8
  "@types/node": 24.2.0
  "@types/chrome": ^0.1.4
  
  # Build tools  
  typescript: ^5.9.2
  vite: ^7.1.3
  vitest: 3.2.4
  "@vitest/ui": 3.2.4
  "@vitejs/plugin-react": ^5.0.1
  
  # Styling
  tailwindcss: ^4.1.12
  "@tailwindcss/vite": ^4.1.12
  
  # React ecosystem
  react: 19.0.0
  "react-dom": 19.0.0
  
  # Testing
  "@playwright/test": ^1.55.0
  
  # Effect/OpenTelemetry  
  effect: 3.17.9
  "@effect/opentelemetry": 0.56.4
  "@opentelemetry/api": 1.9.0
  
  # Common utilities
  graphql: 16.11.0
  
  # Cloudflare tools
  wrangler: ^4.32.0
  "@cloudflare/workers-types": 4.20250823.0
