import { defineConfig } from 'vite-plus'

export default defineConfig({
  run: {
    cache: {
      // Package scripts remain uncached unless they are intentionally wrapped by
      // one of the cache-safe tasks below.
      scripts: false,
      tasks: true,
    },
    tasks: {
      'ci:lint': {
        command: 'pnpm run lint:full',
        output: [],
      },
      'ci:type-check': {
        command: 'pnpm run ts:build',
        input: [{ auto: true }, '!**/*.tsbuildinfo'],
        output: [],
      },
      'ci:test-unit': {
        command: 'vp test',
        // This suite includes randomized property tests and Docker-backed checks,
        // so replaying a previous pass would hide nondeterministic failures.
        cache: false,
      },
    },
  },
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    semi: false,
    singleQuote: true,
    printWidth: 120,
    tabWidth: 2,
    useTabs: false,
    trailingComma: 'all',
    experimentalSortImports: {
      groups: ['builtin', 'external', 'internal', ['parent', 'sibling', 'index']],
      internalPattern: ['@livestore/', '@local/'],
      newlinesBetween: true,
    },
    experimentalSortPackageJson: true,
    ignorePatterns: [
      '**/node_modules/**',
      '**/.pnpm/**',
      '**/.pnpm-store/**',
      '**/.yarn/**',
      '.changeset/**',
      'examples/**',
      '**/dist/**',
      '**/storybook-static/**',
      '**/.turbo/**',
      '**/tmp/**',
      '**/*.gen.ts',
      '**/*.gen.tsx',
      '**/*.generated.ts',
      '**/*.generated.tsx',
      '**/package.json',
      '**/tsconfig.json',
      '**/tsconfig.*.json',
      '**/node_modules/**',
      '**/.pnpm/**',
      '**/.pnpm-store/**',
      '**/.yarn/**',
      'tests/integration/node_modules/**',
      '**/*.mdx',
      'docs/.astro/**',
      'docs/.netlify/**',
      '**/playwright-report/**',
      '**/test-results/**',
    ],
  },
  lint: {
    plugins: ['import', 'typescript', 'unicorn', 'oxc', 'react', 'react', 'react-perf'],
    jsPlugins: [
      './scripts/oxlint-plugin/overeng/mod.ts',
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    ignorePatterns: [
      '**/node_modules/**',
      '**/.pnpm/**',
      '**/.pnpm-store/**',
      '**/.yarn/**',
      'examples/**',
      '**/dist/**',
      '**/build/**',
      '**/out/**',
      '**/.wrangler/**',
      '**/.vercel/**',
      '**/.netlify/**',
      '**/.astro/**',
      '**/.nitro/**',
      '**/.tanstack/**',
      '**/.devenv/**',
      '**/tmp/**',
      '**/playwright-report/**',
      '**/test-results/**',
      '**/nix/**',
      '**/wip/**',
      '**/.vite/**',
      '**/patches/**',
      '**/.cache/**',
      '**/.turbo/**',
      'tests/integration/node_modules/**',
      'docs/src/plugins/**',
    ],
    categories: {
      correctness: 'error',
      suspicious: 'warn',
      pedantic: 'off',
      perf: 'warn',
      style: 'off',
      restriction: 'off',
    },
    rules: {
      'import/no-commonjs': 'error',
      'typescript/consistent-type-imports': 'warn',
      // Oxlint 1.72 enables these through its expanded default categories, but the
      // repository intentionally uses Effect `_tag` fields, scoped shadowing, and
      // debugger helpers. Keep the lint policy from before the Vite+ migration.
      'no-debugger': 'off',
      'no-shadow': 'off',
      'no-underscore-dangle': 'off',
      'react/no-array-index-key': 'off',
      'no-param-reassign': 'error',
      'default-param-last': 'error',
      'typescript/prefer-enum-initializers': 'error',
      'react/self-closing-comp': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/no-inferrable-types': 'error',
      'unicorn/no-array-callback-reference': 'off',
      'typescript/no-explicit-any': 'off',
      'typescript/no-deprecated': 'off',
      'typescript/consistent-type-definitions': 'off',
      'no-unused-vars': 'off',
      eqeqeq: 'off',
      'react/react-in-jsx-scope': 'off',
      'func-style': 'error',
      'oxc/no-barrel-file': 'off',
      'import/default': 'off',
      'import/no-cycle': 'off',
      'import/no-dynamic-require': 'off',
      'import/no-unassigned-import': 'off',
      'import/namespace': 'off',
      'import/no-named-as-default': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'error',
      'react-perf/jsx-no-new-object-as-prop': 'error',
      'react-perf/jsx-no-jsx-as-prop': 'error',
      'react-perf/jsx-no-new-array-as-prop': 'error',
      'block-scoped-var': 'off',
      'no-await-in-loop': 'off',
      'no-unused-expressions': 'off',
      'require-yield': 'off',
      'unicorn/require-post-message-target-origin': 'off',
      'unicorn/prefer-add-event-listener': 'off',
      'unicorn/no-empty-file': 'off',
      'typescript/no-unsafe-type-assertion': 'off',
      'typescript/no-unnecessary-boolean-literal-compare': 'off',
      'typescript/no-unnecessary-type-arguments': 'off',
      'typescript/no-duplicate-type-constituents': 'error',
      'typescript/restrict-template-expressions': 'error',
      'typescript/no-floating-promises': 'off',
      'typescript/no-base-to-string': 'error',
      'typescript/no-redundant-type-constituents': 'error',
      'typescript/no-unnecessary-template-expression': 'error',
      'typescript/no-meaningless-void-operator': 'error',
      'typescript/unbound-method': 'off',
      'typescript/no-misused-spread': 'off',
      'typescript/no-for-in-array': 'off',
      'no-extraneous-class': 'off',
      'triple-slash-reference': 'off',
      'no-new': 'off',
      'no-empty-pattern': 'off',
      'no-useless-catch': 'off',
      'no-unused-private-class-members': 'off',
      'no-unassigned-vars': 'off',
      'no-unneeded-ternary': 'off',
      'no-unexpected-multiline': 'off',
      'no-extend-native': 'off',
      'oxc/only-used-in-recursion': 'off',
      'oxc/const-comparisons': 'off',
      'oxc/no-map-spread': 'off',
      'oxc/no-accumulating-spread': 'off',
      'constructor-super': 'off',
      'react/jsx-key': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/no-new-array': 'off',
      'import/named': 'off',
      'import/export': 'off',
      'vite-plus/prefer-vite-plus-imports': 'error',
      // The newer tsgolint bundled with Vite+ reports these more aggressively
      // than the repository's previous Oxlint version. Keep type-aware linting
      // enabled while avoiding a migration-wide source refactor.
      'typescript/consistent-return': 'off',
      'typescript/no-unnecessary-type-assertion': 'off',
      'typescript/no-unnecessary-type-conversion': 'off',
      'typescript/no-unnecessary-type-parameters': 'off',
      'typescript/no-useless-default-assignment': 'off',
    },
    overrides: [
      {
        files: ['**/*.cjs', '**/*.cts', '**/*.js'],
        rules: {
          'import/no-commonjs': 'off',
        },
      },
      {
        files: ['**/docs/src/content/_assets/code/**'],
        rules: {
          'import/no-commonjs': 'off',
        },
      },
      {
        files: ['**/vitest.config.ts', '**/vite.config.ts', '**/playwright.config.ts'],
        rules: {
          'func-style': 'off',
        },
      },
      {
        files: ['**/*.test.ts', '**/*.test.tsx', '**/__tests__/**', '**/tests/**'],
        rules: {
          'unicorn/no-array-sort': 'off',
          'unicorn/consistent-function-scoping': 'off',
          'require-yield': 'off',
        },
      },
      {
        files: ['**/*.d.ts'],
        rules: {
          'typescript/consistent-type-imports': 'off',
        },
      },
      {
        files: ['**/*.gen.*', '**/.astro/**', '**/routeTree.gen.ts'],
        rules: {
          'func-style': 'off',
          'import/no-commonjs': 'off',
          'import/no-named-as-default': 'off',
          'import/no-unassigned-import': 'off',
          'oxc/no-barrel-file': 'off',
          'oxc/no-map-spread': 'off',
          'unicorn/consistent-function-scoping': 'off',
        },
      },
      {
        files: ['**/wa-sqlite/**'],
        rules: {
          'func-style': 'off',
          'import/no-commonjs': 'off',
          'typescript/await-thenable': 'off',
          'unicorn/no-new-array': 'off',
          'unicorn/no-array-sort': 'off',
          'unicorn/consistent-function-scoping': 'off',
          'no-param-reassign': 'off',
        },
      },
      {
        files: ['**/*.svelte'],
        rules: {
          'import/no-unassigned-import': 'off',
        },
      },
    ],
    options: {
      typeAware: true,
      // tsgo currently reports false positives across this solution-style monorepo
      // (including fixture module shims) even though `tsc --build tsconfig.dev.json`
      // succeeds. Keep type-aware linting and use `vp run ts:build` for type checks.
      typeCheck: false,
    },
  },
})
