# https://electric-sql.com/docs/guides/installation#using-docker
name: "livestore-electric"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric:latest
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric?sslmode=disable
      ELECTRIC_SECRET: change-me-electric-secret
    ports:
      # We'll bind Electric to port 30000 in order to avoid conflicts with the dev server
      - "30000:3000"
    depends_on:
      - postgres
