name = "example-web-todomvc"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = [
  "enable_request_signal",
  "nodejs_compat",
]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[env.prod]
name = "example-web-todomvc"

[env.dev]
name = "example-web-todomvc-dev"
