import { catalog, livestorePackageDefaults, packageJson } from '../../../genie/repo.ts'

export default packageJson({
  name: '@livestore/utils',
  ...livestorePackageDefaults,
  sideEffects: ['./src/global.ts', './dist/global.js'],
  exports: {
    '.': './src/mod.ts',
    './browser': './src/browser/mod.ts',
    './cuid': {
      browser: './src/cuid/cuid.browser.ts',
      'react-native': './src/cuid/cuid.browser.ts',
      default: './src/cuid/cuid.node.ts',
    },
    './nanoid': './src/nanoid/index.ts',
    './effect': './src/effect/mod.ts',
    './effect/browser': './src/browser/mod.ts',
    './node': './src/node/mod.ts',
    './bun': './src/bun/mod.ts',
  },
  dependencies: {
    ...catalog.pick('@effect/platform-node', '@standard-schema/spec', 'nanoid', 'pretty-bytes', 'qrcode-generator'),
  },
  devDependencies: {
    ...catalog.pick(
      '@effect/ai',
      '@effect/cli',
      '@effect/cluster',
      '@effect/experimental',
      '@effect/opentelemetry',
      '@effect/platform',
      '@effect/platform-browser',
      '@effect/platform-bun',
      '@effect/platform-node',
      '@effect/printer',
      '@effect/printer-ansi',
      '@effect/rpc',
      '@effect/sql',
      '@effect/typeclass',
      '@effect/vitest',
      '@effect/workflow',
      '@opentelemetry/api',
      '@opentelemetry/resources',
      '@types/bun',
      '@types/jsdom',
      '@types/node',
      '@types/web',
      'effect',
      'jsdom',
      'vitest',
    ),
  },
  peerDependencies: {
    '@effect/ai': '^0.29.0',
    '@effect/cli': '^0.71.0',
    '@effect/cluster': '^0.50.6',
    '@effect/experimental': '^0.56.0',
    '@effect/opentelemetry': '^0.58.0',
    '@effect/platform': '^0.92.1',
    '@effect/platform-browser': '^0.72.0',
    '@effect/platform-bun': '^0.81.1',
    '@effect/platform-node': '^0.98.4',
    '@effect/printer': '^0.46.0',
    '@effect/printer-ansi': '^0.46.0',
    '@effect/rpc': '^0.71.1',
    '@effect/sql': '^0.46.0',
    '@effect/typeclass': '^0.37.0',
    '@opentelemetry/api': '^1.9.0',
    '@opentelemetry/resources': '^2.0.1',
    effect: '^3.19.9',
  },
  publishConfig: {
    access: 'public',
    exports: {
      '.': {
        types: './dist/mod.d.ts',
        default: './dist/mod.js',
      },
      './browser': {
        types: './dist/browser/mod.d.ts',
        default: './dist/browser/mod.js',
      },
      './cuid': {
        types: './dist/cuid/cuid.node.d.ts',
        browser: './dist/cuid/cuid.browser.js',
        'react-native': './dist/cuid/cuid.browser.js',
        default: './dist/cuid/cuid.node.js',
      },
      './nanoid': {
        types: './dist/nanoid/index.d.ts',
        default: './dist/nanoid/index.js',
      },
      './effect': {
        types: './dist/effect/mod.d.ts',
        default: './dist/effect/mod.js',
      },
      './effect/browser': {
        types: './dist/browser/mod.d.ts',
        default: './dist/browser/mod.js',
      },
      './node': {
        types: './dist/node/mod.d.ts',
        default: './dist/node/mod.js',
      },
      './bun': {
        types: './dist/bun/mod.d.ts',
        default: './dist/bun/mod.js',
      },
    },
  },
  'react-native': './dist/index.js',
  scripts: {
    test: 'vitest',
  },
})
