
style: {
  fill: transparent
}

vars: {
  # https://d2lang.com/tour/themes/#customizing-themes
  # Currently D2 only supports hex colors
  d2-config: {
    theme-overrides: {
      B1: "#7e2a0c" # accent-900
      B2: "#9f2d00" # accent-800
      B3: "#ca3500" # accent-700
      B4: "#f54900" # accent-600
      B5: "#ff8904" # accent-400
      B6: "#ffedd4" # accent-100

      AA2: "#242823" # gray-800
      AA4: "#555954" # gray-500
      AA5: "#c0c3c0" # gray-300

      AB4: "#888d87" # gray-400
      AB5: "#eceeec" # gray-200
    }

    dark-theme-overrides: {
      B1: "#ffd6a7" # accent-200
      B2: "#ffb86a" # accent-300
      B3: "#ff8904" # accent-400
      B4: "#f54900" # accent-600
      B5: "#9f2d00" # accent-800
      B6: "#441306" # accent-950

      AA2: "#eceeec" # gray-200
      AA4: "#888d87" # gray-400
      AA5: "#363935" # gray-700

      AB4: "#c0c3c0" # gray-300
      AB5: "#f5f6f5" # gray-100
    }
  }
}
