/**
 * Stable composition contract for peer repos.
 *
 * Keep this file self-contained (no nested repo imports) so composed megarepos
 * can import it without requiring nested megarepo sync.
 */

/** Workspace packages exposed by LiveStore. */
export const livestoreWorkspaceCatalog = {
  '@livestore/utils': 'workspace:*',
  '@livestore/utils-dev': 'workspace:*',
  '@livestore/common': 'workspace:*',
  '@livestore/common-cf': 'workspace:*',
  '@livestore/livestore': 'workspace:*',
  '@livestore/react': 'workspace:*',
  '@livestore/solid': 'workspace:*',
  '@livestore/svelte': 'workspace:*',
  '@livestore/adapter-web': 'workspace:*',
  '@livestore/adapter-node': 'workspace:*',
  '@livestore/adapter-expo': 'workspace:*',
  '@livestore/adapter-cloudflare': 'workspace:*',
  '@livestore/sqlite-wasm': 'workspace:*',
  '@livestore/webmesh': 'workspace:*',
  '@livestore/devtools-web-common': 'workspace:*',
  '@livestore/devtools-expo': 'workspace:*',
  '@livestore/graphql': 'workspace:*',
  '@livestore/sync-cf': 'workspace:*',
  '@livestore/sync-s2': 'workspace:*',
  '@livestore/sync-electric': 'workspace:*',
  '@livestore/cli': 'workspace:*',
  '@livestore/effect-playwright': 'workspace:*',
  '@livestore/framework-toolkit': 'workspace:*',
  '@livestore/peer-deps': 'workspace:*',
  '@livestore/wa-sqlite': 'workspace:*',

  '@local/astro-tldraw': 'workspace:*',
  '@local/astro-twoslash-code': 'workspace:*',
  '@local/shared': 'workspace:*',
  '@local/docs': 'workspace:*',
  '@local/scripts': 'workspace:*',
  '@local/tests-integration': 'workspace:*',
  '@local/tests-package-common': 'workspace:*',
  '@local/tests-perf': 'workspace:*',
  '@local/tests-perf-streaming-loopback': 'workspace:*',
  '@local/tests-sync-provider': 'workspace:*',
  '@local/tests-wa-sqlite': 'workspace:*',
} as const

/** LiveStore-only versions not provided by effect-utils base catalog. */
export const livestoreOnlyCatalog = {
  '@livestore/devtools-vite': '0.4.0-dev.22',
  '@biomejs/biome': '2.3.8',
  '@types/chrome': '0.1.4',
  '@types/web': '0.0.264',
  '@types/hast': '3.0.4',
  '@types/jasmine': '5.1.4',
  '@types/jsdom': '21.1.7',
  '@types/wicg-file-system-access': '2023.10.6',
  '@vitest/ui': '3.2.4',
  'solid-js': '1.9.10',
  '@solidjs/testing-library': '0.8.10',
  '@testing-library/dom': '10.4.1',
  '@testing-library/jest-dom': '6.6.3',
  '@testing-library/svelte': '5.2.4',
  '@web/dev-server': '0.4.6',
  '@web/test-runner': '0.20.0',
  '@web/test-runner-core': '0.13.4',
  'jasmine-core': '4.5.0',
  jsdom: '26.1.0',
  'web-test-runner-jasmine': '0.0.6',
  '@effect/ai-openai': '0.39.0',
  '@effect/platform-browser': '0.76.0',
  '@effect/platform-bun': '0.89.0',
  '@effect/platform-node-shared': '0.59.0',
  '@effect/sql-sqlite-node': '0.52.0',
  '@opentelemetry/context-zone': '2.2.0',
  '@opentelemetry/core': '2.2.0',
  '@opentelemetry/exporter-metrics-otlp-grpc': '0.208.0',
  '@opentelemetry/exporter-metrics-otlp-http': '0.208.0',
  '@opentelemetry/exporter-trace-otlp-grpc': '0.208.0',
  '@opentelemetry/exporter-trace-otlp-http': '0.208.0',
  '@opentelemetry/otlp-exporter-base': '0.208.0',
  '@opentelemetry/otlp-transformer': '0.208.0',
  graphql: '16.11.0',
  comlink: '4.4.1',
  'react-window': '1.8.11',
  'monaco-editor': '0.34.1',
  nanoid: '5.0.9',
  'pretty-bytes': '7.0.1',
  'qrcode-generator': '1.4.4',
  '@standard-schema/spec': '1.0.0',
  '@iarna/toml': '3.0.0',
  '@graphql-typed-document-node/core': '3.2.0',
  'astro-expressive-code': '0.41.5',
  'expressive-code': '0.41.5',
  'expressive-code-twoslash': '0.5.3',
  hast: '1.0.0',
  'hast-util-to-html': '9.0.4',
  '@kitschpatrol/tldraw-cli': '5.0.1',
  rollup: '4.49.0',
  '@rollup/plugin-commonjs': '28.0.6',
  '@rollup/plugin-node-resolve': '16.0.1',
  '@rollup/plugin-terser': '0.4.4',
  svelte: '5.43.14',
  '@sveltejs/vite-plugin-svelte': '6.2.1',
  astro: '5.13.4',
  '@astrojs/starlight': '0.35.2',
  typedoc: '0.28.11',
  expo: '54.0.12',
  'expo-application': '7.0.7',
  'expo-sqlite': '16.0.8',
  'react-native': '0.81.4',
  wrangler: '4.42.2',
  '@cloudflare/workers-types': '4.20251118.0',
  husky: '9.1.7',
  madge: '8.0.0',
  yaml: '2.8.1',
} as const

const livestorePackageNames = [
  'adapter-cloudflare',
  'adapter-expo',
  'adapter-node',
  'adapter-web',
  'cli',
  'common',
  'common-cf',
  'devtools-expo',
  'devtools-web-common',
  'effect-playwright',
  'framework-toolkit',
  'graphql',
  'livestore',
  'peer-deps',
  'react',
  'solid',
  'sqlite-wasm',
  'svelte',
  'sync-cf',
  'sync-electric',
  'sync-s2',
  'utils',
  'utils-dev',
  'wa-sqlite',
  'webmesh',
] as const

const toCamelCase = (value: string) => value.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase())

/** Internal refs for consumers that need path mappings to @livestore packages. */
export const createLivestoreRefs = (basePath: string) =>
  Object.fromEntries(livestorePackageNames.map((name) => [toCamelCase(name), { path: `${basePath}/${name}` }]))
