name = "websocket-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2024-05-12"

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync-cf-demo"
database_id = "1c9b5dae-f1fa-49d8-83fa-7bd5b39c4121"
# database_id = "${LIVESTORE_CF_SYNC_DATABASE_ID}"

[env.prod]
name = "websocket-server"

[env.dev]
name = "websocket-server-dev"

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
