name = "livestore-email-client-prototype"
main = "src/cf-worker/index.ts"
compatibility_date = "2025-08-24"

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[[d1_databases]]
binding = "DB"
database_name = "email-client-prototype-demo"
database_id = "199c832c-755e-4d4b-ac86-3026b11607e0"

[observability]
enabled = true
