import { Schema } from '@livestore/utils/effect'

import { UnknownError } from '../errors.ts'
import { EventSequenceNumber } from '../schema/mod.ts'

export class IsOfflineError extends Schema.TaggedError<IsOfflineError>()('IsOfflineError', {
  cause: Schema.Defect,
}) {}

/** Unique ID generated by the backend when its created. Used to check whether the backend identity has changed. */
export const BackendId = Schema.String.annotations({ title: '@livestore/sync-cf:BackendId' })

export class BackendIdMismatchError extends Schema.TaggedError<BackendIdMismatchError>()('BackendIdMismatchError', {
  expected: BackendId,
  received: BackendId,
}) {}

export class ServerAheadError extends Schema.TaggedError<ServerAheadError>()('ServerAheadError', {
  minimumExpectedNum: EventSequenceNumber.Global.Schema,
  providedNum: EventSequenceNumber.Global.Schema,
}) {}

export class InvalidPushError extends Schema.TaggedError<InvalidPushError>()('InvalidPushError', {
  cause: Schema.Union(UnknownError, ServerAheadError, BackendIdMismatchError),
}) {}

export class InvalidPullError extends Schema.TaggedError<InvalidPullError>()('InvalidPullError', {
  cause: Schema.Union(UnknownError, BackendIdMismatchError),
}) {}

/**
 * A pushed batch of events failed validation because its sequence numbers are not strictly increasing.
 *
 * @remarks
 *
 * This is a defensive check — callers are expected to construct monotonic event batches.
 * The client should rebase and retry.
 */
export class NonMonotonicBatchError extends Schema.TaggedError<NonMonotonicBatchError>()(
  'NonMonotonicBatchError',
  {
    /** The sequence number that broke the monotonic invariant (i.e. the one that is >= the next). */
    precedingSeqNum: EventSequenceNumber.Client.Composite,
    /** The sequence number that was expected to be greater than `precedingSeqNum`. */
    violatingSeqNum: EventSequenceNumber.Client.Composite,
    /** The index in the batch where the violation occurred. */
    violationIndex: Schema.Number,
    /** The session that produced the malformed batch. */
    sessionId: Schema.String,
  },
) {
  override get message(): string {
    return `Pushed events' sequence numbers are not strictly increasing at index ${this.violationIndex} (session ${this.sessionId}): ${EventSequenceNumber.Client.toString(this.precedingSeqNum)} >= ${EventSequenceNumber.Client.toString(this.violatingSeqNum)}`
  }
}

/**
 * A pushed batch of events failed validation because its rebase generation is older than the leader's current rebase generation.
 *
 * @remarks
 *
 * This happens when events were enqueued before a backend-pull-triggered rebase incremented the generation.
 */
export class StaleRebaseGenerationError extends Schema.TaggedError<StaleRebaseGenerationError>()(
  'StaleRebaseGenerationError',
  {
    /** The leader's current rebase generation. */
    currentRebaseGeneration: Schema.Number,
    /** The rebase generation carried by the dropped events. */
    providedRebaseGeneration: Schema.Number,
    /** The session that produced the stale batch. */
    sessionId: Schema.String,
  },
) {
  override get message(): string {
    return `Pushed events have stale rebase generation (session ${this.sessionId}): expected >= ${this.currentRebaseGeneration}, got ${this.providedRebaseGeneration}`
  }
}

export class LeaderAheadError extends Schema.TaggedError<LeaderAheadError>()('LeaderAheadError', {
  minimumExpectedNum: EventSequenceNumber.Client.Composite,
  providedNum: EventSequenceNumber.Client.Composite,
  /** Generation number the client session should use for subsequent pushes */
  // nextGeneration: Schema.Number,
}) {}

export const SyncError = Schema.Union(InvalidPushError, InvalidPullError)
export type SyncError = typeof SyncError.Type
