// NOTE This file is auto-generated by ./src/drizzle/gen-drizzle.ts based on the schema in ./src/schema.ts

import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const todos = sqliteTable('todos', {
  id: text('id').primaryKey(),
  text: text('text').notNull().default(''),
  completed: integer('completed', { mode: 'boolean' }).notNull().default(false),
})

export const app = sqliteTable('app', {
  id: text('id').primaryKey(),
  newTodoText: text('newTodoText').default(''),
  filter: text('filter').notNull().default('all'),
})

export const __livestore_event_cursor = sqliteTable('__livestore_event_cursor', {
  id: text('id').primaryKey(),
  cursor: text('cursor').notNull(),
})

export const __livestore_schema = sqliteTable('__livestore_schema', {
  tableName: text('tableName').primaryKey(),
  schemaHash: integer('schemaHash').notNull(),
  updatedAt: text('updatedAt').notNull(),
})
