sequenceDiagram
    box ClientSession
        participant UI
        participant Store
        participant CSSP as ClientSessionSyncProcessor
        participant InMemorySQLite
        participant LeaderPushQueue
    end
    box Leader
        participant ClientSessionPullQueues
        participant LSP as LeaderSyncProcessor
        participant PersistedSQLite
        participant BackendPushQueue
    end
    box Backend
        participant SyncBackend
    end

    LSP->>SyncBackend: pull events from backend pull stream
    LSP->>LSP: Merge events as 'upstream-advance'

    Note over LSP: merge result = 'rebase'

    LSP->>BackendPushQueue: clear and restart with rebased pending events
    LSP->>PersistedSQLite: rollback conflicting events
    LSP->>ClientSessionPullQueues: broadcast 'upstream-rebase'<br>to client sessions

    LSP->>PersistedSQLite: materialize upstream events

    ClientSessionPullQueues->>CSSP: PayloadUpstreamRebase
    CSSP->>CSSP: Merge payload as 'upstream-rebase'

    Note over CSSP: merge result = 'rebase'

    CSSP->>CSSP: stop leader pushing
    CSSP->>LeaderPushQueue: clear pending events

    CSSP->>InMemorySQLite: rollback conflicting events using session changesets

    CSSP->>Store: materialize events callback for new upstream events
    Store->>InMemorySQLite: materialize events

    CSSP->>LeaderPushQueue: re-queue rebased pending events
    CSSP->>CSSP: resume leader pushing

    CSSP->>Store: refresh tables callback
    Store->>Store: update table refs
    Store->>UI: trigger reactivity
