sequenceDiagram
    box ClientSession
        participant Store
        participant CSSP as ClientSessionSyncProcessor
        participant ClientSessionSQLite
        participant LeaderPushQueue
    end
    box Leader
        participant LSP as LeaderSyncProcessor
        participant LeaderSQLite
        participant ClientSessionPullQueues
        participant BackendPushQueue
    end
    box Backend
        participant SyncBackend
    end

    LSP->>SyncBackend: pull events from backend pull stream
    LSP->>LSP: Merge events as 'upstream-advance'

    Note over LSP: merge result = 'rebase'

    LSP->>BackendPushQueue: clear and restart with rebased pending events
    LSP->>LeaderSQLite: rollback conflicting events
    LSP->>ClientSessionPullQueues: broadcast PayloadUpstreamRebase to client sessions

    LSP->>LeaderSQLite: materialize upstream events

    ClientSessionPullQueues->>CSSP: PayloadUpstreamRebase
    CSSP->>CSSP: Merge payload as 'upstream-rebase'

    Note over CSSP: merge result = 'rebase'

    CSSP->>CSSP: stop leader pushing
    CSSP->>LeaderPushQueue: clear pending events

    CSSP->>ClientSessionSQLite: rollback conflicting events using session changesets

    CSSP->>Store: materialize events callback for new upstream events
    Store->>ClientSessionSQLite: execute SQLite statements

    CSSP->>LeaderPushQueue: re-queue rebased pending events
    CSSP->>CSSP: resume leader pushing

    CSSP->>Store: refreshTables() callback
    Store->>Store: update table refs & trigger reactivity
