name = "example-web-todomvc-script"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = [
  "enable_request_signal",
  "nodejs_compat",
]

[assets]
directory = "./dist/client"
binding = "ASSETS"

[env.prod]
name = "example-web-todomvc-script"

[env.dev]
name = "example-web-todomvc-script-dev"

[env.preview]
name = "example-web-todomvc-script-preview"

[observability]
enabled = true
