# Netlify configuration for docs deployment
#
# Note: Our deploy scripts execute Netlify CLI with CWD set to the docs app
# directory. Paths below are therefore relative to this folder.
#
# This file also configures Netlify's Image CDN to allow remote image
# transformations from the hosted asset service used for example screenshots.

[images]
# Allow image transformations from gitbucket.schickling.dev
# This is needed for example screenshots to display properly in production
# The domain is double-escaped as required by Netlify's regex configuration
remote_images = ["https://gitbucket\\.schickling\\.dev/.*"]

# Build & publish
# Let the Netlify CLI run the build so it can bundle and attach Edge Functions
# reliably in CI. Astro's static/SSR build does not emit the final edge bundle;
# Netlify's build phase does. We also anchor publish to the docs app so the CLI
# resolves paths consistently in monorepos.
[build]
# Use the docs/ folder as base so publish/edge paths resolve relative to it
# base = "."
publish = "docs/dist"
edge_functions = "docs/netlify/edge-functions"

# Edge Function configuration. The Edge runtime bundles the file(s) below and
# attaches them at the CDN layer during the Netlify build phase.

[[edge_functions]]
function = "markdown-negotiation"
path = "/*"
