name: Enforce Main Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "PR source branch: ${{ github.head_ref }}"
          echo "PR target branch: ${{ github.base_ref }}"
          
          if [ "${{ github.base_ref }}" = "main" ] && [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Error: Pull requests to main branch must come from dev branch"
            echo "Current source branch: ${{ github.head_ref }}"
            echo "Required source branch: dev"
            exit 1
          fi
          
          echo "✅ Source branch validation passed"