name: Renovate Post-Process

on:
  pull_request:
    types: [synchronize]

jobs:
  syncpack-fix:
    if: |
      github.event.pull_request.user.login == 'renovate[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write

    concurrency:
      group: renovate-post-process-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Use FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Load environment with direnv
        uses: HatsuneMiku3939/direnv-action@v1
        timeout-minutes: 5

      - name: Install dependencies
        run: pnpm install

      - name: Run syncpack fix
        run: |
          syncpack fix-mismatches
          syncpack format

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if [ -n "$(git diff --cached --name-only)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -m "chore: run syncpack fix after renovate update"
          git push origin ${{ github.event.pull_request.head.ref }}